services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - ${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - backend

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
